name: live

on:
  push:
    branches:
      - live

jobs:
  live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: ##region##
      - name: Compile Ts to Js
        run: npm run compile
      - name: Compile Ts to Js
        run: npm run compile
      - name: SAM build
        run: sam build
      - name: SAM deploy
        run: sam deploy --guided
